version: '3'

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql:8.0.27
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
    image: jboss/keycloak:15.0.2
    command:
      [
          '-b',
          '0.0.0.0',
#          '-Dkeycloak.migration.action=import',
#          '-Dkeycloak.migration.provider=dir',
#          '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
#          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
#          '-Djboss.socket.binding.port-offset=1000',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
          '-Dkeycloak.profile.feature.declarative_user_profile=enabled',
      ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 9080:8080
      - 9443:9443
      - 10990:10990
      - 9990:9990
    depends_on:
      - mysql

#      [
#          '-b',
#          '0.0.0.0',
#          '-Dkeycloak.migration.action=import',
#          '-Dkeycloak.migration.provider=dir',
#          '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
#          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
#          '-Djboss.socket.binding.port-offset=1000',
#          '-Dkeycloak.profile.feature.upload_scripts=enabled',
#      ]
